# Generated by Django 5.2.17 on 2026-08-16 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academics.department')),
            ],
            options={
                'ordering': ['semester_number'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True)),
                ('course_title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('HS', 'Humanities & Social Sciences'), ('BS', 'Basic Sciences'), ('ES', 'Engineering Sciences'), ('PC', 'Professional Core'), ('OE', 'Open Elective'), ('PE', 'Professional Elective')], db_index=True, max_length=4)),
                ('course_type', models.CharField(choices=[('THEORY', 'Theory'), ('LAB_ORIENTED_THEORY', 'Lab-Oriented Theory')], db_index=True, max_length=24)),
                ('l', models.PositiveSmallIntegerField(default=0, verbose_name='theory periods (L)')),
                ('t', models.PositiveSmallIntegerField(default=0, verbose_name='tutorial periods (T)')),
                ('p', models.PositiveSmallIntegerField(default=0, verbose_name='practical periods (P)')),
                ('credits', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.semester')),
            ],
            options={
                'ordering': ['semester__semester_number', 'course_type', 'course_code', 'course_title'],
            },
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(fields=('department', 'semester_number'), name='uniq_department_semester'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['semester', 'course_type'], name='academics_s_semeste_8e511a_idx'),
        ),
    ]
