# Generated by Django 5.2.17 on 2026-08-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['is_active', 'name'], name='academics_d_is_acti_d3996b_idx'),
        ),
    ]
