# Generated by Django 5.2.17 on 2026-08-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_department_options_department_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='course_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='course_type',
            field=models.CharField(choices=[('THEORY', 'Theory'), ('LAB_ORIENTED_THEORY', 'Lab-Oriented Theory'), ('LABORATORY', 'Laboratory')], db_index=True, max_length=24),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(condition=models.Q(('course_code__isnull', False)), fields=('semester', 'course_code'), name='uniq_semester_course_code'),
        ),
    ]
