# Generated by Django 5.2.17 on 2026-08-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_subject_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('HS', 'Humanities & Social Sciences'), ('HSMC', 'Humanities, Social Sciences & Management'), ('HSM', 'Humanities & Management'), ('MC', 'Mandatory Course'), ('MS', 'Management Studies'), ('BS', 'Basic Sciences'), ('ES', 'Engineering Sciences'), ('PC', 'Professional Core'), ('OE', 'Open Elective'), ('PE', 'Professional Elective')], db_index=True, max_length=4),
        ),
    ]
