# Generated by Django 5.2.4 on 2026-09-05 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0005_alter_subject_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=120)),
                ('state', models.CharField(choices=[('AWAITING_DEPARTMENT', 'Awaiting department'), ('AWAITING_SEMESTER', 'Awaiting semester'), ('AWAITING_SUBJECT_CHOICE', 'Awaiting subject choice'), ('IDLE', 'Idle')], default='AWAITING_DEPARTMENT', max_length=32)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.department')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.semester')),
            ],
            options={
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='WaMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=128, unique=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp.wacontact')),
            ],
        ),
    ]
