# Generated by Django 5.2.17 on 2026-08-16 09:37

import django.db.models.deletion
import resources.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('UNIT_1', 'Unit 1'), ('UNIT_2', 'Unit 2'), ('UNIT_3', 'Unit 3'), ('UNIT_4', 'Unit 4'), ('UNIT_5', 'Unit 5'), ('CAT_1', 'CAT 1'), ('CAT_2', 'CAT 2'), ('SEMESTER_EXAM', 'Semester Exam')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='', max_length=1000)),
                ('file', models.FileField(max_length=255, upload_to=resources.models.resource_upload_path)),
                ('file_name', models.CharField(max_length=200)),
                ('file_type', models.CharField(max_length=120)),
                ('file_ext', models.CharField(max_length=10)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='academics.subject')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subject', 'resource_type'], name='resources_r_subject_9e6bcf_idx'), models.Index(fields=['-created_at'], name='resources_r_created_83a7af_idx')],
            },
        ),
    ]
