# Generated by Django 5.2.4 on 2026-09-05 09:53

import resources.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_subject_category'),
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='kind',
            field=models.CharField(choices=[('NOTES', 'Notes'), ('REFERENCE', 'Reference link'), ('YOUTUBE', 'YouTube video')], db_index=True, default='NOTES', max_length=12),
        ),
        migrations.AddField(
            model_name='resource',
            name='url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, default='', max_length=255, upload_to=resources.models.resource_upload_path),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file_ext',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file_type',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['subject', 'resource_type', 'kind'], name='resources_r_subject_d85195_idx'),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'NOTES'), models.Q(('file', ''), _negated=True), ('url', '')), models.Q(models.Q(('kind', 'NOTES'), _negated=True), ('file', ''), models.Q(('url', ''), _negated=True)), _connector='OR'), name='resource_file_xor_url'),
        ),
    ]
